services:
  mysql:
    image: mysql
    container_name: "electroscoot-rental-db"
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
    volumes:
      - ../src/main/resources/schema.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ../src/main/resources/data.sql:/docker-entrypoint-initdb.d/dml.sql
      - ./docker-healthcheck:/usr/local/bin/docker-healthcheck
    healthcheck:
      test: ["CMD", 'docker-healthcheck']
      timeout: "30s"
      retries: 20
      start_period: "60s"

  app:
    image: spring-boot-app
    container_name: "electroscoot-rental-app"
    build: ../
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: "service_healthy"

  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    ports:
      - "8081:8080"
